// Regenerated by `pnpm db:types`. Do not edit by hand.
//
// Until `supabase gen types` overwrites this file, the permissive shape
// below lets table queries compile. Real types arrive after generation.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type AnyRow = Record<string, unknown>;

type GenericTable = {
  Row: AnyRow;
  Insert: AnyRow;
  Update: AnyRow;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: Record<string, GenericTable>;
    Views: Record<string, GenericTable>;
    Functions: Record<string, never>;
    Enums: {
      task_status: "todo" | "in_progress" | "done";
      member_role: "owner" | "member";
    };
    CompositeTypes: Record<string, never>;
  };
};
