// Regenerated by `pnpm db:types`. Do not edit by hand.
//
// Until `supabase gen types` overwrites this file, the permissive shape
// below lets table queries compile. Real types arrive after generation.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type AnyRow = Record<string, unknown>;

type GenericTable = {
  Row: AnyRow;
  Insert: AnyRow;
  Update: AnyRow;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: Record<string, GenericTable>;
    Views: Record<string, GenericTable>;
    Functions: {
      rpc_create_workspace: {
        Args: { workspace_name: string };
        Returns: string;
      };
      rpc_create_project: {
        Args: { target_workspace_id: string; project_name: string };
        Returns: string;
      };
      rpc_delete_task: {
        Args: { target_task_id: string };
        Returns: undefined;
      };
      rpc_delete_project: {
        Args: { target_project_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      task_status: "todo" | "in_progress" | "done";
      member_role: "owner" | "member";
    };
    CompositeTypes: Record<string, never>;
  };
};
